### ISSUE TITLE
Need maps deleted from database

### ISSUE THREAD

**Issue by Theodorelankford** [spqr-game/spqr-issues#56]
**Details:**
With the new map editor these maps need to be fully removed as there is no delete option present.
19
21
27
28
29
31
32
33
34
37
38
39
40
41
42
43
44
45
46
47
48
49
50

**Expected result:**
These maps made with old editor not to be present

**Actual result:**
These maps are malformed and need to be removed

**Comment by chad3814** [comment]
these 8 maps won't be able to be deleted because games were started with them:
```
+-----------+-------+
| count(id) | mapId |
+-----------+-------+
|         1 |    19 |
|         1 |    21 |
|         1 |    38 |
|         1 |    39 |
|         3 |    41 |
|         1 |    45 |
|         1 |    46 |
|         1 |    50 |
+-----------+-------+
8 rows in set (0.001 sec)
```

**Comment by chad3814** [comment]
I removed the other ones.
